### ISSUE TITLE
type not registered

### ISSUE THREAD

**Issue by HyunmokMoon** [gustavoeb/fabricUtils#14]
Hello,

I modified environment.sh. add to preset/DFG path of our component DFG folder. 
And add exts path of our path.

We can see this log after canvas.sh call.

...
[FABRIC:MT] Loading Canvas presets from /usr/local/src/fabricUtils/DFG
...
[FABRIC:MT] Registered extension {fabricUtils:0.0.3} in directory: /usr/local/src/fabricUtils

I load graph "Samples/bvhReader.canvas".
I get error message in Description.

Location                                                          Description
LoadBVHCharacter_1.BVHReader_1             port 'result': 'BVHReader': type not registered
...

I found why type not registered error.
in /Converters folder, there are kl files with start the Capital character. 
in fabricUtils.fpm.json file, there is file name list. 
all files in /Converters folder are start with small character. 
But a few files start Capital character. e.g. Vec3ToSafeVec3.kl, ScalarToSafeScalar.kl, QuatToSafeQuat.kl.

After I change this file name start with small character, (Vec3ToSafeVec3.kl -> vec3ToSafeVec3.kl, ...)
then exts has no error message, and sample canvas also no error message.

Thank you.

Thank you.
Hyunmok Moon.

**Comment by gustavoeb** [comment]
You are right. Thanks for the heads up. I'll upload this changes in the next commit.
Best,
Gustavo
